/* This is code generated by @frourio/vinext. Do not edit directly. */
import { type NextRequest, NextResponse } from 'vinext/shims/server';
import type { z } from 'zod';
import type { ParamsType, NextParams } from './frourio.params';
import { middleware } from './route.middleware';
import { frourioSpec } from './frourio';
import type { GET } from './route';

type RouteChecker = [typeof GET];

type SpecType = typeof frourioSpec;

type Controller = {
  get: (
    req: {
      params: ParamsType;
      query: z.infer<SpecType['get']['query']>;
    },
  ) => Promise<NextResponse | Response>;
};

type MethodHandler = (req: NextRequest | Request, option: { params: Promise<NextParams<ParamsType>> }) => Promise<NextResponse>;

type ResHandler = {
  GET: MethodHandler
};

export const createRoute = (controller: Controller): ResHandler => {
  const runMiddleware = middleware;

  return {
    GET: runMiddleware(async ({ req, params }) => {
      const url = new URL(req.url);
      const query = frourioSpec.get.query.safeParse({
        'message': url.searchParams.get('message') ?? undefined,
      });

      if (query.error) return createReqErr(query.error);

      const res = await controller.get({ query: query.data, params });

      return res instanceof NextResponse ? res : new NextResponse(res.body, res);
    }),
  };
};

type FrourioError =
  | { status: 422; error: string; issues: { path: (string | number)[]; message: string }[] }
  | { status: 500; error: string; issues?: undefined };

const createReqErr = (err: z.ZodError) =>
  NextResponse.json<FrourioError>(
    {
      status: 422,
      error: 'Unprocessable Entity',
      issues: err.issues.map((issue) => ({ path: issue.path.filter(p => typeof p !== 'symbol'), message: issue.message })),
    },
    { status: 422 },
  );

const createResErr = () =>
  NextResponse.json<FrourioError>(
    { status: 500, error: 'Internal Server Error' },
    { status: 500 },
  );
