/* This is code generated by @frourio/vinext. Do not edit directly. */
import { type NextRequest, NextResponse } from 'vinext/shims/server';
import type { z } from 'zod';
import { paramsSchema, type ParamsType, type NextParams } from './frourio.params';
import { middleware as ancestorMiddleware } from '../../route.middleware';

type MiddlewareFn = (
  args: {
    req: NextRequest | Request,
    params: ParamsType,
    next: () => Promise<NextResponse>,
  },
) => Promise<NextResponse>;

type MiddlewareHandler = (
  next: (args: { req: NextRequest | Request, params: ParamsType }) => Promise<NextResponse>,
) => (req: NextRequest | Request, option: { params: Promise<NextParams<ParamsType>> }) => Promise<NextResponse>;

export const createMiddleware = (middlewareFn: MiddlewareFn): MiddlewareHandler => {
  return (
    next: (args: { req: NextRequest | Request, params: ParamsType }) => Promise<NextResponse>,
  ) => async (req: NextRequest | Request, option: { params: Promise<NextParams<ParamsType>> }) => {
    const params = paramsSchema.safeParse(await option.params);

    if (params.error) return createReqErr(params.error);

    return ancestorMiddleware(async () => {
    return await middlewareFn(
      {
        req,
        params: params.data,
        next: async () => {


      return await next({ req, params: params.data })
      },
      },
    )
    })(req)
  };
};

type FrourioError =
  | { status: 422; error: string; issues: { path: (string | number)[]; message: string }[] }
  | { status: 500; error: string; issues?: undefined };

const createReqErr = (err: z.ZodError) =>
  NextResponse.json<FrourioError>(
    {
      status: 422,
      error: 'Unprocessable Entity',
      issues: err.issues.map((issue) => ({ path: issue.path.filter(p => typeof p !== 'symbol'), message: issue.message })),
    },
    { status: 422 },
  );
