/* This is code generated by @frourio/vinext. Do not edit directly. */
import { type NextRequest, NextResponse } from 'vinext/shims/server';
import type { z } from 'zod';
import { paramsSchema } from './frourio.params';
import type { ParamsType, NextParams } from './frourio.params';
import { middleware as ancestorMiddleware } from '../route.middleware';
import { contextSchema as ancestorContextSchema } from '../frourio.middleware';
import type { ContextType } from '../frourio.middleware';
import { frourioSpec } from './frourio';
import type { GET } from './route';

type RouteChecker = [typeof GET];

type SpecType = typeof frourioSpec;

type Controller = {
  get: (
    req: {
      params: ParamsType;
      query: z.infer<SpecType['get']['query']>;
    },
    ctx: ContextType,
  ) => Promise<
    | {
        status: 200;
        body: z.infer<SpecType['get']['res'][200]['body']>;
      }
  >;
};

type MethodHandler = (req: NextRequest | Request, option: { params: Promise<NextParams<ParamsType>> }) => Promise<NextResponse>;

type ResHandler = {
  GET: MethodHandler
};

export const createRoute = (controller: Controller): ResHandler => {
  const runMiddleware = (next: (
    args: { req: NextRequest | Request, params: ParamsType },
    ctx: ContextType,
  ) => Promise<NextResponse>): MethodHandler => async (req, option) => {
    const params = paramsSchema.safeParse(await option.params);

    if (params.error) return createReqErr(params.error);

    return ancestorMiddleware(async (_, ancestorContext) => {
      const ancestorCtx = ancestorContextSchema.safeParse(ancestorContext);

      if (ancestorCtx.error) return createReqErr(ancestorCtx.error);


      return await next({ req, params: params.data }, { ...ancestorCtx.data, })

    })(req)
  };

  return {
    GET: runMiddleware(async ({ req, params }, ctx) => {
      const url = new URL(req.url);
      const query = frourioSpec.get.query.safeParse({
        'requiredNum': queryToNum(url.searchParams.get('requiredNum') ?? undefined),
        'requiredNumArr': queryToNumArr(url.searchParams.getAll('requiredNumArr')),
        'id': url.searchParams.get('id') ?? undefined,
        'strArray': url.searchParams.getAll('strArray'),
        'disable': url.searchParams.get('disable') ?? undefined,
        'bool': queryToBool(url.searchParams.get('bool') ?? undefined),
        'boolArray': queryToBoolArr(url.searchParams.getAll('boolArray')),
        'symbolIds': url.searchParams.getAll('symbolIds'),
        'maybeIds': queryToNumArr(url.searchParams.getAll('maybeIds')),
        'optionalNum': queryToNum(url.searchParams.get('optionalNum') ?? undefined),
        'optionalNumArr': url.searchParams.getAll('optionalNumArr').length > 0 ? queryToNumArr(url.searchParams.getAll('optionalNumArr')) : undefined,
        'emptyNum': queryToNum(url.searchParams.get('emptyNum') ?? undefined),
        'optionalStrArray': url.searchParams.getAll('optionalStrArray').length > 0 ? url.searchParams.getAll('optionalStrArray') : undefined,
        'optionalBool': queryToBool(url.searchParams.get('optionalBool') ?? undefined),
        'optionalBoolArray': url.searchParams.getAll('optionalBoolArray').length > 0 ? queryToBoolArr(url.searchParams.getAll('optionalBoolArray')) : undefined,
        'optionalZodIds': url.searchParams.getAll('optionalZodIds').length > 0 ? queryToNumArr(url.searchParams.getAll('optionalZodIds')) : undefined,
      });

      if (query.error) return createReqErr(query.error);

      const res = await controller.get({ query: query.data, params }, ctx);

      switch (res.status) {
        case 200: {
          const body = frourioSpec.get.res[200].body.safeParse(res.body);

          if (body.error) return createResErr();

          return createResponse(body.data, { status: 200 });
        }
        default:
          throw new Error(res.status satisfies never);
      }
    }),
  };
};

const createResponse = (body: unknown, init: ResponseInit): NextResponse => {
  if (
    ArrayBuffer.isView(body) ||
    body === undefined ||
    body === null ||
    body instanceof Blob ||
    body instanceof ArrayBuffer ||
    body instanceof FormData ||
    body instanceof ReadableStream ||
    body instanceof URLSearchParams ||
    typeof body === 'string'
  ) {
    return new NextResponse(body as string, init);
  }

  return NextResponse.json(body, init);
};

type FrourioError =
  | { status: 422; error: string; issues: { path: (string | number)[]; message: string }[] }
  | { status: 500; error: string; issues?: undefined };

const createReqErr = (err: z.ZodError) =>
  NextResponse.json<FrourioError>(
    {
      status: 422,
      error: 'Unprocessable Entity',
      issues: err.issues.map((issue) => ({ path: issue.path.filter(p => typeof p !== 'symbol'), message: issue.message })),
    },
    { status: 422 },
  );

const createResErr = () =>
  NextResponse.json<FrourioError>(
    { status: 500, error: 'Internal Server Error' },
    { status: 500 },
  );

const queryToNum = (val: string | undefined) => {
  const num = Number(val);

  return isNaN(num) ? val : num;
};

const queryToNumArr = (val: string[]) => val.map(queryToNum);

const queryToBool = (val: string | undefined) =>
  val === 'true' ? true : val === 'false' ? false : val;

const queryToBoolArr = (val: string[]) => val.map(queryToBool);
