/* This is code generated by @frourio/vinext. Do not edit directly. */
import { type NextRequest, NextResponse } from 'vinext/shims/server';
import type { z } from 'zod';
import { middleware } from './route.middleware';
import { frourioSpec } from './frourio';
import type { GET, POST } from './route';

const parseCookieHeader = (header: string | null): Record<string, string> => {
  const cookies: Record<string, string> = Object.create(null);

  for (const segment of (header ?? '').split(';')) {
    const separator = segment.indexOf('=');
    if (separator < 0) continue;

    const name = segment.slice(0, separator).trim();
    if (!name || name in cookies) continue;

    let value = segment.slice(separator + 1).trim();
    if (value.startsWith('"') && value.endsWith('"')) value = value.slice(1, -1);

    try {
      cookies[name] = decodeURIComponent(value);
    } catch {
      cookies[name] = value;
    }
  }

  return cookies;
};

type RouteChecker = [typeof GET, typeof POST];

type SpecType = typeof frourioSpec;

type Controller = {
  get: (
    req: {
      headers?: z.infer<SpecType['get']['headers']>;
      cookies?: z.infer<SpecType['get']['cookies']>;
      query?: z.infer<SpecType['get']['query']>;
    },
  ) => Promise<
    | {
        status: 200;
        body: z.infer<SpecType['get']['res'][200]['body']>;
      }
  >;
  post: (
    req: {
    },
  ) => Promise<
    | {
        status: 200;
      }
  >;
};

type MethodHandler = (req: NextRequest | Request) => Promise<NextResponse>;

type ResHandler = {
  GET: MethodHandler
  POST: MethodHandler
};

export const createRoute = (controller: Controller): ResHandler => {
  const runMiddleware = middleware;

  return {
    GET: runMiddleware(async ({ req }) => {
      const headers = ["X-Token","x-user"].some(key => req.headers.has(key)) ? frourioSpec.get.headers.safeParse(Object.fromEntries([...req.headers].map(([key, value]) => [["X-Token","x-user"].find(name => name.toLowerCase() === key) ?? key, value]))) : { data: undefined, error: undefined };

      if (headers.error) return createReqErr(headers.error);

      const cookies = ["session","user"].some(key => Object.hasOwn(parseCookieHeader(req.headers.get('cookie')), key)) ? frourioSpec.get.cookies.safeParse(parseCookieHeader(req.headers.get('cookie'))) : { data: undefined, error: undefined };

      if (cookies.error) return createReqErr(cookies.error);

      const url = new URL(req.url);
      const query = ["count","active"].some(key => url.searchParams.has(key)) ? frourioSpec.get.query.safeParse({
        'count': queryToNum(url.searchParams.get('count') ?? undefined),
        'active': queryToBool(url.searchParams.get('active') ?? undefined),
      }) : { data: undefined, error: undefined };

      if (query.error) return createReqErr(query.error);

      const res = await controller.get({ ...(headers.data === undefined ? {} : { headers: headers.data }), ...(cookies.data === undefined ? {} : { cookies: cookies.data }), ...(query.data === undefined ? {} : { query: query.data }) });

      switch (res.status) {
        case 200: {
          const body = frourioSpec.get.res[200].body.safeParse(res.body);

          if (body.error) return createResErr();

          return createResponse(body.data, { status: 200 });
        }
        default:
          throw new Error(res.status satisfies never);
      }
    }),
    POST: runMiddleware(async ({ req }) => {
      const res = await controller.post({  });

      switch (res.status) {
        case 200: {
          return new NextResponse(null, { status: 200 });
        }
        default:
          throw new Error(res.status satisfies never);
      }
    }),
  };
};

const createResponse = (body: unknown, init: ResponseInit): NextResponse => {
  if (
    ArrayBuffer.isView(body) ||
    body === undefined ||
    body === null ||
    body instanceof Blob ||
    body instanceof ArrayBuffer ||
    body instanceof FormData ||
    body instanceof ReadableStream ||
    body instanceof URLSearchParams ||
    typeof body === 'string'
  ) {
    return new NextResponse(body as string, init);
  }

  return NextResponse.json(body, init);
};

type FrourioError =
  | { status: 422; error: string; issues: { path: (string | number)[]; message: string }[] }
  | { status: 500; error: string; issues?: undefined };

const createReqErr = (err: z.ZodError) =>
  NextResponse.json<FrourioError>(
    {
      status: 422,
      error: 'Unprocessable Entity',
      issues: err.issues.map((issue) => ({ path: issue.path.filter(p => typeof p !== 'symbol'), message: issue.message })),
    },
    { status: 422 },
  );

const createResErr = () =>
  NextResponse.json<FrourioError>(
    { status: 500, error: 'Internal Server Error' },
    { status: 500 },
  );

const queryToNum = (val: string | undefined) => {
  const num = Number(val);

  return isNaN(num) ? val : num;
};

const queryToBool = (val: string | undefined) =>
  val === 'true' ? true : val === 'false' ? false : val;
