/* This is code generated by @frourio/vinext. Do not edit directly. */
import { type NextRequest, NextResponse } from 'vinext/shims/server';
import type { z } from 'zod';
import { frourioSpec } from './frourio';

type MiddlewareFn = (
  args: {
    req: NextRequest | Request,
    headers?: z.infer<typeof frourioSpec.middleware.headers>,
    cookies?: z.infer<typeof frourioSpec.middleware.cookies>,
    query?: z.infer<typeof frourioSpec.middleware.query>,
    next: () => Promise<NextResponse>,
  },
) => Promise<NextResponse>;

type MiddlewareHandler = (
  next: (args: { req: NextRequest | Request }) => Promise<NextResponse>,
) => (req: NextRequest | Request, option?: Record<string, unknown>) => Promise<NextResponse>;

export const createMiddleware = (middlewareFn: MiddlewareFn): MiddlewareHandler => {
  return (
    next: (args: { req: NextRequest | Request }) => Promise<NextResponse>,
  ) => async (req: NextRequest | Request, _option?: Record<string, unknown>) => {

    const headers = ["X-Token","x-user"].some(key => req.headers.has(key)) ? frourioSpec.middleware.headers.safeParse(Object.fromEntries([...req.headers].map(([key, value]) => [["X-Token","x-user"].find(name => name.toLowerCase() === key) ?? key, value]))) : { data: undefined, error: undefined };
    if (headers.error) return createReqErr(headers.error);

    const cookies = ["session","user"].some(key => Object.hasOwn(parseCookieHeader(req.headers.get('cookie')), key)) ? frourioSpec.middleware.cookies.safeParse(parseCookieHeader(req.headers.get('cookie'))) : { data: undefined, error: undefined };
    if (cookies.error) return createReqErr(cookies.error);

    const url = new URL(req.url);
    const query = ["count","active"].some(key => url.searchParams.has(key)) ? frourioSpec.middleware.query.safeParse({
        'count': queryToNum(url.searchParams.get('count') ?? undefined),
        'active': queryToBool(url.searchParams.get('active') ?? undefined),
      }) : { data: undefined, error: undefined };
    if (query.error) return createReqErr(query.error);
    return await middlewareFn(
      {
        req,
        ...(headers.data === undefined ? {} : { headers: headers.data }),
        ...(cookies.data === undefined ? {} : { cookies: cookies.data }),
        ...(query.data === undefined ? {} : { query: query.data }),
        next: async () => {


          return await next({ req });
        },
      },
    );
    
  };
};
const parseCookieHeader = (header: string | null): Record<string, string> => {
  const cookies: Record<string, string> = Object.create(null);

  for (const segment of (header ?? '').split(';')) {
    const separator = segment.indexOf('=');
    if (separator < 0) continue;

    const name = segment.slice(0, separator).trim();
    if (!name || name in cookies) continue;

    let value = segment.slice(separator + 1).trim();
    if (value.startsWith('"') && value.endsWith('"')) value = value.slice(1, -1);

    try {
      cookies[name] = decodeURIComponent(value);
    } catch {
      cookies[name] = value;
    }
  }

  return cookies;
};
const queryToNum = (val: string | undefined) => {
  const num = Number(val);

  return isNaN(num) ? val : num;
};

const queryToBool = (val: string | undefined) =>
  val === 'true' ? true : val === 'false' ? false : val

type FrourioError =
  | { status: 422; error: string; issues: { path: (string | number)[]; message: string }[] }
  | { status: 500; error: string; issues?: undefined };

const createReqErr = (err: z.ZodError) =>
  NextResponse.json<FrourioError>(
    {
      status: 422,
      error: 'Unprocessable Entity',
      issues: err.issues.map((issue) => ({ path: issue.path.filter(p => typeof p !== 'symbol'), message: issue.message })),
    },
    { status: 422 },
  );
