/* This is code generated by @frourio/vinext. Do not edit directly. */
import { type NextRequest, NextResponse } from 'vinext/shims/server';
import type { z } from 'zod';
import { frourioSpec } from './frourio';
import type { GET, POST, PUT, PATCH, DELETE, OPTIONS } from './route';

type RouteChecker = [typeof GET, typeof POST, typeof PUT, typeof PATCH, typeof DELETE, typeof OPTIONS];

type SpecType = typeof frourioSpec;

type Controller = {
  get: (
    req: {
    },
  ) => Promise<
    | {
        status: 200;
        body: z.infer<SpecType['get']['res'][200]['body']>;
      }
    | {
        status: 301;
        headers: z.infer<SpecType['get']['res'][301]['headers']>;
        cookies: z.infer<z.ZodObject<{
          "session": SpecType['get']['res'][301]['cookies']["session"]['value'];
        }>>;
      }
    | {
        status: 304;
        headers: z.infer<SpecType['get']['res'][304]['headers']>;
      }
  >;
  post: (
    req: {
    },
  ) => Promise<
    | {
        status: 307;
        headers: z.infer<SpecType['post']['res'][307]['headers']>;
        body: z.infer<SpecType['post']['res'][307]['body']>;
      }
  >;
  put: (
    req: {
    },
  ) => Promise<
    | {
        status: 200;
        body: z.infer<SpecType['put']['res'][200]['body']>;
      }
    | {
        status: 302;
        headers: z.infer<SpecType['put']['res'][302]['headers']>;
      }
  >;
  patch: (
    req: {
    },
  ) => Promise<
    | {
        status: 308;
      }
  >;
  delete: (
    req: {
    },
  ) => Promise<
    | {
        status: 303;
      }
  >;
  options: (
    req: {
    },
  ) => Promise<
    | {
        status: 300;
        body: z.infer<SpecType['options']['res'][300]['body']>;
      }
  >;
};

type MethodHandler = (req: NextRequest | Request) => Promise<NextResponse>;

type ResHandler = {
  GET: MethodHandler
  POST: MethodHandler
  PUT: MethodHandler
  PATCH: MethodHandler
  DELETE: MethodHandler
  OPTIONS: MethodHandler
};

export const createRoute = (controller: Controller): ResHandler => {
  return {
    GET: async (req) => {
      const res = await controller.get({  });

      switch (res.status) {
        case 200: {
          const body = frourioSpec.get.res[200].body.safeParse(res.body);

          if (body.error) return createResErr();

          return createResponse(body.data, { status: 200 });
        }
        case 301: {
          const headers = frourioSpec.get.res[301].headers.safeParse(res.headers);

          if (headers.error) return createResErr();

          const cookies0 = frourioSpec.get.res[301].cookies["session"].value.safeParse(res.cookies?.["session"]);

          if (cookies0.error) return createResErr();

          const response = new NextResponse(null, { status: 301, headers: headers.data });

          if (cookies0.data !== undefined) {
            response.cookies.set({ name: "session", value: String(cookies0.data) });
          }

          return response;
        }
        case 304: {
          const headers = frourioSpec.get.res[304].headers.safeParse(res.headers);

          if (headers.error) return createResErr();

          return new NextResponse(null, { status: 304, headers: headers.data });
        }
        default:
          throw new Error(res satisfies never);
      }
    },
    POST: async (req) => {
      const res = await controller.post({  });

      switch (res.status) {
        case 307: {
          const headers = frourioSpec.post.res[307].headers.safeParse(res.headers);

          if (headers.error) return createResErr();

          const body = frourioSpec.post.res[307].body.safeParse(res.body);

          if (body.error) return createResErr();

          return createResponse(body.data, { status: 307, headers: headers.data });
        }
        default:
          throw new Error(res.status satisfies never);
      }
    },
    PUT: async (req) => {
      const res = await controller.put({  });

      switch (res.status) {
        case 200: {
          const body = frourioSpec.put.res[200].body.safeParse(res.body);

          if (body.error) return createResErr();

          return createResponse(body.data, { status: 200 });
        }
        case 302: {
          const headers = frourioSpec.put.res[302].headers.safeParse(res.headers);

          if (headers.error) return createResErr();

          return new NextResponse(null, { status: 302, headers: headers.data });
        }
        default:
          throw new Error(res satisfies never);
      }
    },
    PATCH: async (req) => {
      const res = await controller.patch({  });

      switch (res.status) {
        case 308: {
          return new NextResponse(null, { status: 308 });
        }
        default:
          throw new Error(res.status satisfies never);
      }
    },
    DELETE: async (req) => {
      const res = await controller.delete({  });

      switch (res.status) {
        case 303: {
          return new NextResponse(null, { status: 303 });
        }
        default:
          throw new Error(res.status satisfies never);
      }
    },
    OPTIONS: async (req) => {
      const res = await controller.options({  });

      switch (res.status) {
        case 300: {
          const body = frourioSpec.options.res[300].body.safeParse(res.body);

          if (body.error) return createResErr();

          return createResponse(body.data, { status: 300 });
        }
        default:
          throw new Error(res.status satisfies never);
      }
    },
  };
};

const createResponse = (body: unknown, init: ResponseInit): NextResponse => {
  if (
    ArrayBuffer.isView(body) ||
    body === undefined ||
    body === null ||
    body instanceof Blob ||
    body instanceof ArrayBuffer ||
    body instanceof FormData ||
    body instanceof ReadableStream ||
    body instanceof URLSearchParams ||
    typeof body === 'string'
  ) {
    return new NextResponse(body as string, init);
  }

  return NextResponse.json(body, init);
};

type FrourioError =
  | { status: 422; error: string; issues: { path: (string | number)[]; message: string }[] }
  | { status: 500; error: string; issues?: undefined };

const createReqErr = (err: z.ZodError) =>
  NextResponse.json<FrourioError>(
    {
      status: 422,
      error: 'Unprocessable Entity',
      issues: err.issues.map((issue) => ({ path: issue.path.filter(p => typeof p !== 'symbol'), message: issue.message })),
    },
    { status: 422 },
  );

const createResErr = () =>
  NextResponse.json<FrourioError>(
    { status: 500, error: 'Internal Server Error' },
    { status: 500 },
  );
