/* This is code generated by @frourio/vinext. Do not edit directly. */
import { type NextRequest, NextResponse } from 'vinext/shims/server';
import type { z } from 'zod';
import { frourioSpec } from './frourio';

type MiddlewareFn = (
  args: {
    req: NextRequest | Request,
    headers: z.infer<typeof frourioSpec.middleware.headers>,
    cookies: z.infer<typeof frourioSpec.middleware.cookies>,
    query: z.infer<typeof frourioSpec.middleware.query>,
    next: () => Promise<NextResponse>,
  },
) => Promise<NextResponse>;

type MiddlewareHandler = (
  next: (args: { req: NextRequest | Request }) => Promise<NextResponse>,
) => (req: NextRequest | Request, option?: Record<string, unknown>) => Promise<NextResponse>;

export const createMiddleware = (middlewareFn: MiddlewareFn): MiddlewareHandler => {
  return (
    next: (args: { req: NextRequest | Request }) => Promise<NextResponse>,
  ) => async (req: NextRequest | Request, _option?: Record<string, unknown>) => {

    const headers = frourioSpec.middleware.headers.safeParse(Object.fromEntries(req.headers));
    if (headers.error) return createReqErr(headers.error);

    const cookies = frourioSpec.middleware.cookies.safeParse(parseCookieHeader(req.headers.get('cookie')));
    if (cookies.error) return createReqErr(cookies.error);

    const url = new URL(req.url);
    const query = frourioSpec.middleware.query.safeParse({
        'count': queryToNum(url.searchParams.get('count') ?? undefined),
        'active': queryToBool(url.searchParams.get('active') ?? undefined),
        'ids': queryToNumArr(url.searchParams.getAll('ids')),
        'flags': url.searchParams.getAll('flags').length > 0 ? queryToBoolArr(url.searchParams.getAll('flags')) : undefined,
        'label': url.searchParams.get('label') ?? undefined,
      });
    if (query.error) return createReqErr(query.error);
    return await middlewareFn(
      {
        req,
        headers: headers.data,
        cookies: cookies.data,
        query: query.data,
        next: async () => {


          return await next({ req });
        },
      },
    );
    
  };
};
const parseCookieHeader = (header: string | null): Record<string, string> => {
  const cookies: Record<string, string> = Object.create(null);

  for (const segment of (header ?? '').split(';')) {
    const separator = segment.indexOf('=');
    if (separator < 0) continue;

    const name = segment.slice(0, separator).trim();
    if (!name || name in cookies) continue;

    let value = segment.slice(separator + 1).trim();
    if (value.startsWith('"') && value.endsWith('"')) value = value.slice(1, -1);

    try {
      cookies[name] = decodeURIComponent(value);
    } catch {
      cookies[name] = value;
    }
  }

  return cookies;
};
const queryToNum = (val: string | undefined) => {
  const num = Number(val);

  return isNaN(num) ? val : num;
};

const queryToNumArr = (val: string[]) => val.map(queryToNum);

const queryToBool = (val: string | undefined) =>
  val === 'true' ? true : val === 'false' ? false : val;

const queryToBoolArr = (val: string[]) => val.map(queryToBool)

type FrourioError =
  | { status: 422; error: string; issues: { path: (string | number)[]; message: string }[] }
  | { status: 500; error: string; issues?: undefined };

const createReqErr = (err: z.ZodError) =>
  NextResponse.json<FrourioError>(
    {
      status: 422,
      error: 'Unprocessable Entity',
      issues: err.issues.map((issue) => ({ path: issue.path.filter(p => typeof p !== 'symbol'), message: issue.message })),
    },
    { status: 422 },
  );
