/* This is code generated by @frourio/vinext. Do not edit directly. */
import { z } from 'zod';
import { frourioSpec } from './frourio';

const paramToNum = <T extends z.ZodTypeAny>(schema: T) => z.preprocess(Number, schema);

export const paramsSchema = z.object({ 'a': paramToNum(frourioSpec.param) });

export type ParamsType = z.infer<typeof paramsSchema>;

export type NextParams<T extends Record<string, unknown>> = {
  [Key in keyof T]: (NonNullable<T[Key]> extends unknown[] ? string[] : string) | T[Key];
};
