/* This is code generated by @frourio/vinext. Do not edit directly. */
import { type NextRequest, NextResponse } from 'vinext/shims/server';
import type { z } from 'zod';
import { frourioSpec } from './frourio';
import type { GET, POST } from './route';

const parseCookieHeader = (header: string | null): Record<string, string> => {
  const cookies: Record<string, string> = Object.create(null);

  for (const segment of (header ?? '').split(';')) {
    const separator = segment.indexOf('=');
    if (separator < 0) continue;

    const name = segment.slice(0, separator).trim();
    if (!name || name in cookies) continue;

    let value = segment.slice(separator + 1).trim();
    if (value.startsWith('"') && value.endsWith('"')) value = value.slice(1, -1);

    try {
      cookies[name] = decodeURIComponent(value);
    } catch {
      cookies[name] = value;
    }
  }

  return cookies;
};

type RouteChecker = [typeof GET, typeof POST];

type SpecType = typeof frourioSpec;

type Controller = {
  get: (
    req: {
      cookies: z.infer<SpecType['get']['cookies']>;
    },
  ) => Promise<
    | {
        status: 200;
        body: z.infer<SpecType['get']['res'][200]['body']>;
      }
  >;
  post: (
    req: {
      cookies: z.infer<SpecType['post']['cookies']>;
      body: z.infer<SpecType['post']['body']>;
    },
  ) => Promise<
    | {
        status: 200;
        headers: z.infer<SpecType['post']['res'][200]['headers']>;
        cookies: z.infer<z.ZodObject<{
          "val": SpecType['post']['res'][200]['cookies']["val"]['value'];
          "enabled": SpecType['post']['res'][200]['cookies']["enabled"]['value'];
          "count": SpecType['post']['res'][200]['cookies']["count"]['value'];
        }>>;
      }
    | {
        status: 400;
      }
  >;
};

type MethodHandler = (req: NextRequest | Request) => Promise<NextResponse>;

type ResHandler = {
  GET: MethodHandler
  POST: MethodHandler
};

export const createRoute = (controller: Controller): ResHandler => {
  return {
    GET: async (req) => {
      const cookies = frourioSpec.get.cookies.safeParse(parseCookieHeader(req.headers.get('cookie')));

      if (cookies.error) return createReqErr(cookies.error);

      const res = await controller.get({ cookies: cookies.data });

      switch (res.status) {
        case 200: {
          const body = frourioSpec.get.res[200].body.safeParse(res.body);

          if (body.error) return createResErr();

          const response = createResponse(body.data, { status: 200 });

          response.cookies.delete({ name: "legacy" });

          return response;
        }
        default:
          throw new Error(res.status satisfies never);
      }
    },
    POST: async (req) => {
      const cookies = frourioSpec.post.cookies.safeParse(parseCookieHeader(req.headers.get('cookie')));

      if (cookies.error) return createReqErr(cookies.error);

      const body = frourioSpec.post.body.safeParse(await req.json().catch(() => undefined));

      if (body.error) return createReqErr(body.error);

      const res = await controller.post({ cookies: cookies.data, body: body.data });

      switch (res.status) {
        case 200: {
          const headers = frourioSpec.post.res[200].headers.safeParse(res.headers);

          if (headers.error) return createResErr();

          const cookies0 = frourioSpec.post.res[200].cookies["val"].value.safeParse(res.cookies?.["val"]);

          if (cookies0.error) return createResErr();

          const cookies1 = frourioSpec.post.res[200].cookies["enabled"].value.safeParse(res.cookies?.["enabled"]);

          if (cookies1.error) return createResErr();

          const cookies2 = frourioSpec.post.res[200].cookies["count"].value.safeParse(res.cookies?.["count"]);

          if (cookies2.error) return createResErr();

          const response = new NextResponse(null, { status: 200, headers: headers.data });

          if (cookies0.data !== undefined) {
            response.cookies.set({ name: "val", value: String(cookies0.data) });
          }

          if (cookies1.data !== undefined) {
            response.cookies.set({ name: "enabled", value: String(cookies1.data) });
          }

          if (cookies2.data !== undefined) {
            response.cookies.set({ ...frourioSpec.post.res[200].cookies["count"].options, name: "count", value: String(cookies2.data) });
          }

          response.cookies.delete({ ...frourioSpec.post.res[200].cookies["legacy"].options, name: "legacy" });

          return response;
        }
        case 400: {
          return new NextResponse(null, { status: 400 });
        }
        default:
          throw new Error(res satisfies never);
      }
    },
  };
};

const createResponse = (body: unknown, init: ResponseInit): NextResponse => {
  if (
    ArrayBuffer.isView(body) ||
    body === undefined ||
    body === null ||
    body instanceof Blob ||
    body instanceof ArrayBuffer ||
    body instanceof FormData ||
    body instanceof ReadableStream ||
    body instanceof URLSearchParams ||
    typeof body === 'string'
  ) {
    return new NextResponse(body as string, init);
  }

  return NextResponse.json(body, init);
};

type FrourioError =
  | { status: 422; error: string; issues: { path: (string | number)[]; message: string }[] }
  | { status: 500; error: string; issues?: undefined };

const createReqErr = (err: z.ZodError) =>
  NextResponse.json<FrourioError>(
    {
      status: 422,
      error: 'Unprocessable Entity',
      issues: err.issues.map((issue) => ({ path: issue.path.filter(p => typeof p !== 'symbol'), message: issue.message })),
    },
    { status: 422 },
  );

const createResErr = () =>
  NextResponse.json<FrourioError>(
    { status: 500, error: 'Internal Server Error' },
    { status: 500 },
  );
