/* This is code generated by @frourio/vinext. Do not edit directly. */
import { type NextRequest, NextResponse } from 'vinext/shims/server';
import type { z } from 'zod';
import type { FrourioResponseCookies } from '@frourio/vinext';
import { frourioSpec } from './frourio';
import type { GET, POST } from './route';

const parseCookieHeader = (header: string | null): Record<string, string> => {
  const cookies: Record<string, string> = Object.create(null);

  for (const segment of (header ?? '').split(';')) {
    const separator = segment.indexOf('=');
    if (separator < 0) continue;

    const name = segment.slice(0, separator).trim();
    if (!name || name in cookies) continue;

    let value = segment.slice(separator + 1).trim();
    if (value.startsWith('"') && value.endsWith('"')) value = value.slice(1, -1);

    try {
      cookies[name] = decodeURIComponent(value);
    } catch {
      cookies[name] = value;
    }
  }

  return cookies;
};

type RouteChecker = [typeof GET, typeof POST];

type SpecType = typeof frourioSpec;

type Controller = {
  get: (
    req: {
      cookies: z.infer<SpecType['get']['cookies']>;
    },
  ) => Promise<
    | {
        status: 200;
        cookies: FrourioResponseCookies<SpecType['get']['res'][200]['cookies']>;
        body: z.infer<SpecType['get']['res'][200]['body']>;
      }
  >;
  post: (
    req: {
      cookies: z.infer<SpecType['post']['cookies']>;
      body: z.infer<SpecType['post']['body']>;
    },
  ) => Promise<
    | {
        status: 201;
        cookies?: FrourioResponseCookies<SpecType['post']['res'][201]['cookies']>;
      }
    | {
        status: 200;
        headers: z.infer<SpecType['post']['res'][200]['headers']>;
        cookies: FrourioResponseCookies<SpecType['post']['res'][200]['cookies']>;
      }
    | {
        status: 400;
      }
  >;
};

type MethodHandler = (req: NextRequest | Request) => Promise<NextResponse>;

type ResHandler = {
  GET: MethodHandler
  POST: MethodHandler
};

export const createRoute = (controller: Controller): ResHandler => {
  return {
    GET: async (req) => {
      const cookies = frourioSpec.get.cookies.safeParse(parseCookieHeader(req.headers.get('cookie')));

      if (cookies.error) return createReqErr(cookies.error);

      const res = await controller.get({ cookies: cookies.data });

      switch (res.status) {
        case 200: {
          const body = frourioSpec.get.res[200].body.safeParse(res.body);

          if (body.error) return createResErr();

          const cookie0 = res.cookies?.["legacy"];
          if ((!cookie0 || cookie0.command !== 'delete')) return createResErr();


          const response = createResponse(body.data, { status: 200 });

          if (cookie0 !== undefined) response.cookies.delete({ ...cookie0?.options, name: "legacy" });

          return response;
        }
        default:
          throw new Error(res.status satisfies never);
      }
    },
    POST: async (req) => {
      const cookies = frourioSpec.post.cookies.safeParse(parseCookieHeader(req.headers.get('cookie')));

      if (cookies.error) return createReqErr(cookies.error);

      const body = frourioSpec.post.body.safeParse(await req.json().catch(() => undefined));

      if (body.error) return createReqErr(body.error);

      const res = await controller.post({ cookies: cookies.data, body: body.data });

      switch (res.status) {
        case 201: {
          const cookie0 = res.cookies?.["optionalLegacy"];
          if (cookie0 !== undefined && (!cookie0 || cookie0.command !== 'delete')) return createResErr();


          const response = new NextResponse(null, { status: 201 });

          if (cookie0 !== undefined) response.cookies.delete({ ...cookie0?.options, name: "optionalLegacy" });

          return response;
        }
        case 200: {
          const headers = frourioSpec.post.res[200].headers.safeParse(res.headers);

          if (headers.error) return createResErr();

          const cookie0 = res.cookies?.["val"];
          if ((!cookie0 || cookie0.command !== 'set')) return createResErr();
          const cookies0 = cookie0 === undefined ? undefined : frourioSpec.post.res[200].cookies["val"].value.safeParse(cookie0.value);
          if (cookies0?.error) return createResErr();

          const cookie1 = res.cookies?.["enabled"];
          if (cookie1 !== undefined && (!cookie1 || cookie1.command !== 'set')) return createResErr();
          const cookies1 = cookie1 === undefined ? undefined : frourioSpec.post.res[200].cookies["enabled"].value.safeParse(cookie1.value);
          if (cookies1?.error) return createResErr();

          const cookie2 = res.cookies?.["count"];
          if (cookie2 !== undefined && (!cookie2 || cookie2.command !== 'set')) return createResErr();
          const cookies2 = cookie2 === undefined ? undefined : frourioSpec.post.res[200].cookies["count"].value.safeParse(cookie2.value);
          if (cookies2?.error) return createResErr();

          const cookie3 = res.cookies?.["optionalLegacy"];
          if (cookie3 !== undefined && (!cookie3 || cookie3.command !== 'delete')) return createResErr();


          const cookie4 = res.cookies?.["legacy"];
          if ((!cookie4 || cookie4.command !== 'delete')) return createResErr();


          const response = new NextResponse(null, { status: 200, headers: headers.data });

          if (cookies0?.data !== undefined) {
            response.cookies.set({ ...cookie0?.options, name: "val", value: String(cookies0.data) });
          }

          if (cookies1?.data !== undefined) {
            response.cookies.set({ ...cookie1?.options, name: "enabled", value: String(cookies1.data) });
          }

          if (cookies2?.data !== undefined) {
            response.cookies.set({ ...frourioSpec.post.res[200].cookies["count"].options, ...cookie2?.options, name: "count", value: String(cookies2.data) });
          }

          if (cookie3 !== undefined) response.cookies.delete({ ...cookie3?.options, name: "optionalLegacy" });

          if (cookie4 !== undefined) response.cookies.delete({ ...frourioSpec.post.res[200].cookies["legacy"].options, ...cookie4?.options, name: "legacy" });

          return response;
        }
        case 400: {
          return new NextResponse(null, { status: 400 });
        }
        default:
          throw new Error(res satisfies never);
      }
    },
  };
};

const createResponse = (body: unknown, init: ResponseInit): NextResponse => {
  if (
    ArrayBuffer.isView(body) ||
    body === undefined ||
    body === null ||
    body instanceof Blob ||
    body instanceof ArrayBuffer ||
    body instanceof FormData ||
    body instanceof ReadableStream ||
    body instanceof URLSearchParams ||
    typeof body === 'string'
  ) {
    return new NextResponse(body as string, init);
  }

  return NextResponse.json(body, init);
};

type FrourioError =
  | { status: 422; error: string; issues: { path: (string | number)[]; message: string }[] }
  | { status: 500; error: string; issues?: undefined };

const createReqErr = (err: z.ZodError) =>
  NextResponse.json<FrourioError>(
    {
      status: 422,
      error: 'Unprocessable Entity',
      issues: err.issues.map((issue) => ({ path: issue.path.filter(p => typeof p !== 'symbol'), message: issue.message })),
    },
    { status: 422 },
  );

const createResErr = () =>
  NextResponse.json<FrourioError>(
    { status: 500, error: 'Internal Server Error' },
    { status: 500 },
  );
