/* This is code generated by @frourio/vinext. Do not edit directly. */
import { z } from 'zod';
import { paramsSchema as ancestorParamsSchema } from '../../frourio.params';

export const paramsSchema = z.object({ 'c': z.tuple([z.string()]).rest(z.string()) }).and(ancestorParamsSchema).and(z.object({ 'b': z.string() }));

export type ParamsType = z.infer<typeof paramsSchema>;

export type NextParams<T extends Record<string, unknown>> = {
  [Key in keyof T]: (NonNullable<T[Key]> extends unknown[] ? string[] : string) | T[Key];
};
