/* This is code generated by @frourio/vinext. Do not edit directly. */
import { type NextRequest, NextResponse } from 'vinext/shims/server';

type MiddlewareFn = (
  args: {
    req: NextRequest | Request,
    next: () => Promise<NextResponse>,
  },
) => Promise<NextResponse>;

type MiddlewareHandler = (
  next: (args: { req: NextRequest | Request }) => Promise<NextResponse>,
) => (req: NextRequest | Request, option?: Record<string, unknown>) => Promise<NextResponse>;

export const createMiddleware = (middlewareFn: MiddlewareFn): MiddlewareHandler => {
  return (
    next: (args: { req: NextRequest | Request }) => Promise<NextResponse>,
  ) => async (req: NextRequest | Request, _option?: Record<string, unknown>) => {
    return await middlewareFn(
      {
        req,
        next: async () => {


      return await next({ req })
      },
      },
    )
    
  };
};
