/* This is code generated by @frourio/vinext. Do not edit directly. */
import { z } from 'zod';
import { frourioSpec } from './frourio';

const paramToNumArr = <T extends z.ZodTypeAny>(schema: T) =>
  z.preprocess((val) => Array.isArray(val) ? val.map(Number) : val, schema);

export const paramsSchema = z.object({ 'slug': paramToNumArr(frourioSpec.param) });

export type ParamsType = z.infer<typeof paramsSchema>;

export type NextParams<T extends Record<string, unknown>> = {
  [Key in keyof T]: (NonNullable<T[Key]> extends unknown[] ? string[] : string) | T[Key];
};
