/* This is code generated by @frourio/vinext. Do not edit directly. */
import type { FrourioClientOption } from '@frourio/vinext';
import { z } from 'zod';
import { frourioSpec as frourioSpec_dn9cqh } from './[...all]/frourio';
import { frourioSpec as frourioSpec_1rzyav8 } from './[[...optAll]]/frourio';
import { frourioSpec as frourioSpec_og4f3x } from './[a]/arrayBuffer/frourio';
import { frourioSpec as frourioSpec_uq501x } from './[a]/blob/frourio';
import { frourioSpec as frourioSpec_bfn325 } from './[a]/text/frourio';
import { frourioSpec as frourioSpec_36xt6y } from './api/frourio';
import { frourioSpec as frourioSpec_15e5upz } from './api/%E6%97%A5%E6%9C%AC%E8%AA%9E/frourio';
import { frourioSpec as frourioSpec_er79ce } from './(group1)/blog/[...slug]/frourio';
import { frourioSpec as frourioSpec_ztntfp } from './frourio'

export const fc = (option?: FrourioClientOption) => ({
  '[...all]': {
    $url: $url_dn9cqh(option),
    $build(req: Parameters<ReturnType<typeof methods_dn9cqh>['$get']>[0] | null): [
      key: { lowLevel: true; baseURL: FrourioClientOption['baseURL']; dir: string } & Omit<Parameters<ReturnType<typeof methods_dn9cqh>['$get']>[0], 'init'> | null,
      fetcher: () => Promise<NonNullable<Awaited<ReturnType<ReturnType<typeof methods_dn9cqh>['$get']>>>>,
    ] {
      if (req === null) return [null, () => Promise.reject(new Error('Fetcher is disabled.'))];

      const { init, ...rest } = req;

      return [{ lowLevel: true, baseURL: option?.baseURL, dir: '/[...all]', ...rest }, () => methods_dn9cqh(option).$get(req)];
    },
    ...methods_dn9cqh(option),
  },
  '[[...optAll]]': {
    $url: $url_1rzyav8(option),
    $build(req: Parameters<ReturnType<typeof methods_1rzyav8>['$get']>[0] | null): [
      key: { lowLevel: true; baseURL: FrourioClientOption['baseURL']; dir: string } & Omit<Parameters<ReturnType<typeof methods_1rzyav8>['$get']>[0], 'init'> | null,
      fetcher: () => Promise<NonNullable<Awaited<ReturnType<ReturnType<typeof methods_1rzyav8>['$get']>>>>,
    ] {
      if (req === null) return [null, () => Promise.reject(new Error('Fetcher is disabled.'))];

      const { init, ...rest } = req;

      return [{ lowLevel: true, baseURL: option?.baseURL, dir: '/[[...optAll]]', ...rest }, () => methods_1rzyav8(option).$get(req)];
    },
    ...methods_1rzyav8(option),
  },
  '[a]/arrayBuffer': {
    $url: $url_og4f3x(option),
    ...methods_og4f3x(option),
  },
  '[a]/blob': {
    $url: $url_uq501x(option),
    ...methods_uq501x(option),
  },
  '[a]/text': {
    $url: $url_bfn325(option),
    ...methods_bfn325(option),
  },
  'api': {
    $url: $url_36xt6y(option),
    ...methods_36xt6y(option),
  },
  'api/%E6%97%A5%E6%9C%AC%E8%AA%9E': {
    $url: $url_15e5upz(option),
    ...methods_15e5upz(option),
  },
  $url: $url_ztntfp(option),
  $build(req?: { init?: RequestInit }): [
    key: { lowLevel: true; baseURL: FrourioClientOption['baseURL']; dir: string },
    fetcher: () => Promise<NonNullable<Awaited<ReturnType<ReturnType<typeof methods_ztntfp>['$get']>>>>,
  ] {
    return [{ lowLevel: true, baseURL: option?.baseURL, dir: '/' }, () => methods_ztntfp(option).$get(req)];
  },
  ...methods_ztntfp(option),
});

export const $fc = (option?: FrourioClientOption) => ({
  '[...all]': {
    $url: {
      get(req: Parameters<ReturnType<typeof $url_dn9cqh>['get']>[0]): string {
        const result = $url_dn9cqh(option).get(req);

        if (!result.isValid) throw result.reason;

        return result.data;
      },
    },
    $build(req: Parameters<ReturnType<typeof methods_dn9cqh>['$get']>[0] | null): [
      key: { lowLevel: false; baseURL: FrourioClientOption['baseURL']; dir: string } & Omit<Parameters<ReturnType<typeof methods_dn9cqh>['$get']>[0], 'init'> | null,
      fetcher: () => Promise<z.infer<typeof frourioSpec_dn9cqh.get.res[200]['body']>>,
    ] {
      if (req === null) return [null, () => Promise.reject(new Error('Fetcher is disabled.'))];

      const { init, ...rest } = req;

      return [{ lowLevel: false, baseURL: option?.baseURL, dir: '/[...all]', ...rest }, () => $fc(option)['[...all]'].$get(req)];
    },
    async $get(req: Parameters<ReturnType<typeof methods_dn9cqh>['$get']>[0]): Promise<z.infer<typeof frourioSpec_dn9cqh.get.res[200]['body']>> {
      const result = await methods_dn9cqh(option).$get(req);

      if (!result.isValid) throw result.isValid === false ? result.reason : result.error;

      return result.data.body;
    },
  },
  '[[...optAll]]': {
    $url: {
      get(req: Parameters<ReturnType<typeof $url_1rzyav8>['get']>[0]): string {
        const result = $url_1rzyav8(option).get(req);

        if (!result.isValid) throw result.reason;

        return result.data;
      },
    },
    $build(req: Parameters<ReturnType<typeof methods_1rzyav8>['$get']>[0] | null): [
      key: { lowLevel: false; baseURL: FrourioClientOption['baseURL']; dir: string } & Omit<Parameters<ReturnType<typeof methods_1rzyav8>['$get']>[0], 'init'> | null,
      fetcher: () => Promise<z.infer<typeof frourioSpec_1rzyav8.get.res[200]['body']>>,
    ] {
      if (req === null) return [null, () => Promise.reject(new Error('Fetcher is disabled.'))];

      const { init, ...rest } = req;

      return [{ lowLevel: false, baseURL: option?.baseURL, dir: '/[[...optAll]]', ...rest }, () => $fc(option)['[[...optAll]]'].$get(req)];
    },
    async $get(req: Parameters<ReturnType<typeof methods_1rzyav8>['$get']>[0]): Promise<z.infer<typeof frourioSpec_1rzyav8.get.res[200]['body']>> {
      const result = await methods_1rzyav8(option).$get(req);

      if (!result.isValid) throw result.isValid === false ? result.reason : result.error;

      return result.data.body;
    },
  },
  '[a]/arrayBuffer': {
    $url: {
      post(req: Parameters<ReturnType<typeof $url_og4f3x>['post']>[0]): string {
        const result = $url_og4f3x(option).post(req);

        if (!result.isValid) throw result.reason;

        return result.data;
      },
    },
    async $post(req: Parameters<ReturnType<typeof methods_og4f3x>['$post']>[0]): Promise<z.infer<typeof frourioSpec_og4f3x.post.res[200]['body']>> {
      const result = await methods_og4f3x(option).$post(req);

      if (!result.isValid) throw result.isValid === false ? result.reason : result.error;

      return result.data.body;
    },
  },
  '[a]/blob': {
    $url: {
      post(req: Parameters<ReturnType<typeof $url_uq501x>['post']>[0]): string {
        const result = $url_uq501x(option).post(req);

        if (!result.isValid) throw result.reason;

        return result.data;
      },
    },
    async $post(req: Parameters<ReturnType<typeof methods_uq501x>['$post']>[0]): Promise<z.infer<typeof frourioSpec_uq501x.post.res[200]['body']>> {
      const result = await methods_uq501x(option).$post(req);

      if (!result.isValid) throw result.isValid === false ? result.reason : result.error;

      return result.data.body;
    },
  },
  '[a]/text': {
    $url: {
      post(req: Parameters<ReturnType<typeof $url_bfn325>['post']>[0]): string {
        const result = $url_bfn325(option).post(req);

        if (!result.isValid) throw result.reason;

        return result.data;
      },
    },
    async $post(req: Parameters<ReturnType<typeof methods_bfn325>['$post']>[0]): Promise<z.infer<typeof frourioSpec_bfn325.post.res[200]['body']>> {
      const result = await methods_bfn325(option).$post(req);

      if (!result.isValid) throw result.isValid === false ? result.reason : result.error;

      return result.data.body;
    },
  },
  'api': {
    $url: {
      post(): string {
        const result = $url_36xt6y(option).post();

        if (!result.isValid) throw result.reason;

        return result.data;
      },
      put(): string {
        const result = $url_36xt6y(option).put();

        if (!result.isValid) throw result.reason;

        return result.data;
      },
    },
    async $post(req: Parameters<ReturnType<typeof methods_36xt6y>['$post']>[0]): Promise<z.infer<typeof frourioSpec_36xt6y.post.res[200]['body']>> {
      const result = await methods_36xt6y(option).$post(req);

      if (!result.isValid) throw result.isValid === false ? result.reason : result.error;

      return result.data.body;
    },
    async $put(req: Parameters<ReturnType<typeof methods_36xt6y>['$put']>[0]): Promise<z.infer<typeof frourioSpec_36xt6y.put.res[200]['body']>> {
      const result = await methods_36xt6y(option).$put(req);

      if (!result.isValid) throw result.isValid === false ? result.reason : result.error;

      return result.data.body;
    },
  },
  'api/%E6%97%A5%E6%9C%AC%E8%AA%9E': {
    $url: {
      post(): string {
        const result = $url_15e5upz(option).post();

        if (!result.isValid) throw result.reason;

        return result.data;
      },
    },
    async $post(req: Parameters<ReturnType<typeof methods_15e5upz>['$post']>[0]): Promise<z.infer<typeof frourioSpec_15e5upz.post.res[200]['body']>> {
      const result = await methods_15e5upz(option).$post(req);

      if (!result.isValid) throw result.isValid === false ? result.reason : result.error;

      return result.data.body;
    },
  },
  $url: {
    get(): string {
      const result = $url_ztntfp(option).get();

      if (!result.isValid) throw result.reason;

      return result.data;
    },
  },
  $build(req?: { init?: RequestInit }): [
    key: { lowLevel: false; baseURL: FrourioClientOption['baseURL']; dir: string },
    fetcher: () => Promise<z.infer<typeof frourioSpec_ztntfp.get.res[200]['body']>>,
  ] {
    return [{ lowLevel: false, baseURL: option?.baseURL, dir: '/' }, () => $fc(option).$get(req)];
  },
  async $get(req?: Parameters<ReturnType<typeof methods_ztntfp>['$get']>[0]): Promise<z.infer<typeof frourioSpec_ztntfp.get.res[200]['body']>> {
    const result = await methods_ztntfp(option).$get(req);

    if (!result.isValid) throw result.isValid === false ? result.reason : result.error;

    return result.data.body;
  },
});

export const fc_ztntfp = fc;

export const $fc_ztntfp = $fc;

const paramsSchema_dn9cqh = z.object({ 'all': z.tuple([z.string()]).rest(z.string()) });

const paramsSchema_1rzyav8 = z.object({ 'optAll': z.tuple([z.string()]).rest(z.string()).optional() });

const paramsSchema_og4f3x = z.object({ 'a': z.string() });

const paramsSchema_uq501x = z.object({ 'a': z.string() });

const paramsSchema_bfn325 = z.object({ 'a': z.string() });

const $url_ztntfp = (option?: FrourioClientOption) => ({
  get(): { isValid: true; data: string; reason?: undefined } | { isValid: false, data?: undefined; reason: z.ZodError } {
    return { isValid: true, data: `${option?.baseURL?.replace(/\/$/, '') ?? ''}/foo/bar` };
  },
});

const $url_dn9cqh = (option?: FrourioClientOption) => ({
  get(req: { params: z.infer<typeof paramsSchema_dn9cqh> }): { isValid: true; data: string; reason?: undefined } | { isValid: false, data?: undefined; reason: z.ZodError } {
    const parsedParams = paramsSchema_dn9cqh.safeParse(req.params);

    if (!parsedParams.success) return { isValid: false, reason: parsedParams.error };

    return { isValid: true, data: `${option?.baseURL?.replace(/\/$/, '') ?? ''}/foo/bar/${parsedParams.data.all.join('/')}` };
  },
});

const $url_1rzyav8 = (option?: FrourioClientOption) => ({
  get(req: { params: z.infer<typeof paramsSchema_1rzyav8> }): { isValid: true; data: string; reason?: undefined } | { isValid: false, data?: undefined; reason: z.ZodError } {
    const parsedParams = paramsSchema_1rzyav8.safeParse(req.params);

    if (!parsedParams.success) return { isValid: false, reason: parsedParams.error };

    return { isValid: true, data: `${option?.baseURL?.replace(/\/$/, '') ?? ''}/foo/bar${parsedParams.data.optAll !== undefined && parsedParams.data.optAll.length > 0 ? `/${parsedParams.data.optAll.join('/')}` : ''}` };
  },
});

const $url_og4f3x = (option?: FrourioClientOption) => ({
  post(req: { params: z.infer<typeof paramsSchema_og4f3x> }): { isValid: true; data: string; reason?: undefined } | { isValid: false, data?: undefined; reason: z.ZodError } {
    const parsedParams = paramsSchema_og4f3x.safeParse(req.params);

    if (!parsedParams.success) return { isValid: false, reason: parsedParams.error };

    return { isValid: true, data: `${option?.baseURL?.replace(/\/$/, '') ?? ''}/foo/bar/${parsedParams.data.a}/arrayBuffer` };
  },
});

const $url_uq501x = (option?: FrourioClientOption) => ({
  post(req: { params: z.infer<typeof paramsSchema_uq501x> }): { isValid: true; data: string; reason?: undefined } | { isValid: false, data?: undefined; reason: z.ZodError } {
    const parsedParams = paramsSchema_uq501x.safeParse(req.params);

    if (!parsedParams.success) return { isValid: false, reason: parsedParams.error };

    return { isValid: true, data: `${option?.baseURL?.replace(/\/$/, '') ?? ''}/foo/bar/${parsedParams.data.a}/blob` };
  },
});

const $url_bfn325 = (option?: FrourioClientOption) => ({
  post(req: { params: z.infer<typeof paramsSchema_bfn325> }): { isValid: true; data: string; reason?: undefined } | { isValid: false, data?: undefined; reason: z.ZodError } {
    const parsedParams = paramsSchema_bfn325.safeParse(req.params);

    if (!parsedParams.success) return { isValid: false, reason: parsedParams.error };

    return { isValid: true, data: `${option?.baseURL?.replace(/\/$/, '') ?? ''}/foo/bar/${parsedParams.data.a}/text` };
  },
});

const $url_36xt6y = (option?: FrourioClientOption) => ({
  post(): { isValid: true; data: string; reason?: undefined } | { isValid: false, data?: undefined; reason: z.ZodError } {
    return { isValid: true, data: `${option?.baseURL?.replace(/\/$/, '') ?? ''}/foo/bar/api` };
  },
  put(): { isValid: true; data: string; reason?: undefined } | { isValid: false, data?: undefined; reason: z.ZodError } {
    return { isValid: true, data: `${option?.baseURL?.replace(/\/$/, '') ?? ''}/foo/bar/api` };
  },
});

const $url_15e5upz = (option?: FrourioClientOption) => ({
  post(): { isValid: true; data: string; reason?: undefined } | { isValid: false, data?: undefined; reason: z.ZodError } {
    return { isValid: true, data: `${option?.baseURL?.replace(/\/$/, '') ?? ''}/foo/bar/api/%E6%97%A5%E6%9C%AC%E8%AA%9E` };
  },
});

const methods_ztntfp = (option?: FrourioClientOption) => ({
  async $get(req?: { init?: RequestInit }): Promise<
    | { ok: true; isValid: true; data: { status: 200; headers?: undefined; body: z.infer<typeof frourioSpec_ztntfp.get.res[200]['body']> }; failure?: undefined; raw: Response; reason?: undefined; error?: undefined }
    | { ok: boolean; isValid: false; data?: undefined; failure?: undefined; raw: Response; reason: z.ZodError; error?: undefined }
    | { ok: boolean; isValid?: undefined; data?: undefined; failure?: undefined; raw: Response; reason?: undefined; error: unknown }
    | { ok?: undefined; isValid: false; data?: undefined; failure?: undefined; raw?: undefined; reason: z.ZodError; error?: undefined }
    | { ok?: undefined; isValid?: undefined; data?: undefined; failure?: undefined; raw?: undefined; reason?: undefined; error: unknown }
  > {
    const url = $url_ztntfp(option).get();

    if (url.reason) return url;

    const fetchFn = option?.fetch ?? fetch;
    const result: { success: true; res: Response } | { success: false; error: unknown } = await fetchFn(
      url.data,
      {
        method: 'GET',
        ...option?.init,
        ...req?.init,
        headers: { ...option?.init?.headers, ...req?.init?.headers },
      }
    ).then(res => ({ success: true, res } as const)).catch(error => ({ success: false, error }));

    if (!result.success) return { error: result.error };

    switch (result.res.status) {
      case 200: {
        const resBody: { success: true; data: unknown } | { success: false; error: unknown } = await result.res.json().then(data => ({ success: true, data } as const)).catch(error => ({ success: false, error }));

        if (!resBody.success) return { ok: true, raw: result.res, error: resBody.error };

        const body = frourioSpec_ztntfp.get.res[200].body.safeParse(resBody.data);

        if (!body.success) return { ok: true, isValid: false, raw: result.res, reason: body.error };

        return {
          ok: true,
          isValid: true,
          data: { status: 200, body: body.data },
          raw: result.res,
        };
      }
      default:
        return { ok: result.res.ok, raw: result.res, error: new Error(`Unknown status: ${result.res.status}`) };
    }
  },
});

const methods_dn9cqh = (option?: FrourioClientOption) => ({
  async $get(req: { params: z.infer<typeof paramsSchema_dn9cqh>, init?: RequestInit }): Promise<
    | { ok: true; isValid: true; data: { status: 200; headers?: undefined; body: z.infer<typeof frourioSpec_dn9cqh.get.res[200]['body']> }; failure?: undefined; raw: Response; reason?: undefined; error?: undefined }
    | { ok: boolean; isValid: false; data?: undefined; failure?: undefined; raw: Response; reason: z.ZodError; error?: undefined }
    | { ok: boolean; isValid?: undefined; data?: undefined; failure?: undefined; raw: Response; reason?: undefined; error: unknown }
    | { ok?: undefined; isValid: false; data?: undefined; failure?: undefined; raw?: undefined; reason: z.ZodError; error?: undefined }
    | { ok?: undefined; isValid?: undefined; data?: undefined; failure?: undefined; raw?: undefined; reason?: undefined; error: unknown }
  > {
    const url = $url_dn9cqh(option).get(req);

    if (url.reason) return url;

    const fetchFn = option?.fetch ?? fetch;
    const result: { success: true; res: Response } | { success: false; error: unknown } = await fetchFn(
      url.data,
      {
        method: 'GET',
        ...option?.init,
        ...req.init,
        headers: { ...option?.init?.headers, ...req.init?.headers },
      }
    ).then(res => ({ success: true, res } as const)).catch(error => ({ success: false, error }));

    if (!result.success) return { error: result.error };

    switch (result.res.status) {
      case 200: {
        const resBody: { success: true; data: unknown } | { success: false; error: unknown } = await result.res.text().then(data => ({ success: true, data } as const)).catch(error => ({ success: false, error }));

        if (!resBody.success) return { ok: true, raw: result.res, error: resBody.error };

        const body = frourioSpec_dn9cqh.get.res[200].body.safeParse(resBody.data);

        if (!body.success) return { ok: true, isValid: false, raw: result.res, reason: body.error };

        return {
          ok: true,
          isValid: true,
          data: { status: 200, body: body.data },
          raw: result.res,
        };
      }
      default:
        return { ok: result.res.ok, raw: result.res, error: new Error(`Unknown status: ${result.res.status}`) };
    }
  },
});

const methods_1rzyav8 = (option?: FrourioClientOption) => ({
  async $get(req: { params: z.infer<typeof paramsSchema_1rzyav8>, init?: RequestInit }): Promise<
    | { ok: true; isValid: true; data: { status: 200; headers?: undefined; body: z.infer<typeof frourioSpec_1rzyav8.get.res[200]['body']> }; failure?: undefined; raw: Response; reason?: undefined; error?: undefined }
    | { ok: boolean; isValid: false; data?: undefined; failure?: undefined; raw: Response; reason: z.ZodError; error?: undefined }
    | { ok: boolean; isValid?: undefined; data?: undefined; failure?: undefined; raw: Response; reason?: undefined; error: unknown }
    | { ok?: undefined; isValid: false; data?: undefined; failure?: undefined; raw?: undefined; reason: z.ZodError; error?: undefined }
    | { ok?: undefined; isValid?: undefined; data?: undefined; failure?: undefined; raw?: undefined; reason?: undefined; error: unknown }
  > {
    const url = $url_1rzyav8(option).get(req);

    if (url.reason) return url;

    const fetchFn = option?.fetch ?? fetch;
    const result: { success: true; res: Response } | { success: false; error: unknown } = await fetchFn(
      url.data,
      {
        method: 'GET',
        ...option?.init,
        ...req.init,
        headers: { ...option?.init?.headers, ...req.init?.headers },
      }
    ).then(res => ({ success: true, res } as const)).catch(error => ({ success: false, error }));

    if (!result.success) return { error: result.error };

    switch (result.res.status) {
      case 200: {
        const resBody: { success: true; data: unknown } | { success: false; error: unknown } = await result.res.text().then(data => ({ success: true, data } as const)).catch(error => ({ success: false, error }));

        if (!resBody.success) return { ok: true, raw: result.res, error: resBody.error };

        const body = frourioSpec_1rzyav8.get.res[200].body.safeParse(resBody.data);

        if (!body.success) return { ok: true, isValid: false, raw: result.res, reason: body.error };

        return {
          ok: true,
          isValid: true,
          data: { status: 200, body: body.data },
          raw: result.res,
        };
      }
      default:
        return { ok: result.res.ok, raw: result.res, error: new Error(`Unknown status: ${result.res.status}`) };
    }
  },
});

const methods_og4f3x = (option?: FrourioClientOption) => ({
  async $post(req: { params: z.infer<typeof paramsSchema_og4f3x>, body: z.infer<typeof frourioSpec_og4f3x.post.body>, init?: RequestInit }): Promise<
    | { ok: true; isValid: true; data: { status: 200; headers?: undefined; body: z.infer<typeof frourioSpec_og4f3x.post.res[200]['body']> }; failure?: undefined; raw: Response; reason?: undefined; error?: undefined }
    | { ok: boolean; isValid: false; data?: undefined; failure?: undefined; raw: Response; reason: z.ZodError; error?: undefined }
    | { ok: boolean; isValid?: undefined; data?: undefined; failure?: undefined; raw: Response; reason?: undefined; error: unknown }
    | { ok?: undefined; isValid: false; data?: undefined; failure?: undefined; raw?: undefined; reason: z.ZodError; error?: undefined }
    | { ok?: undefined; isValid?: undefined; data?: undefined; failure?: undefined; raw?: undefined; reason?: undefined; error: unknown }
  > {
    const url = $url_og4f3x(option).post(req);

    if (url.reason) return url;

    const parsedBody = frourioSpec_og4f3x.post.body.safeParse(req.body);

    if (!parsedBody.success) return { isValid: false, reason: parsedBody.error };

    const fetchFn = option?.fetch ?? fetch;
    const result: { success: true; res: Response } | { success: false; error: unknown } = await fetchFn(
      url.data,
      {
        method: 'POST',
        ...option?.init,
        body: parsedBody.data,
        ...req.init,
        headers: { ...option?.init?.headers, 'content-type': 'application/octet-stream', ...req.init?.headers },
      }
    ).then(res => ({ success: true, res } as const)).catch(error => ({ success: false, error }));

    if (!result.success) return { error: result.error };

    switch (result.res.status) {
      case 200: {
        const resBody: { success: true; data: unknown } | { success: false; error: unknown } = await result.res.arrayBuffer().then(data => ({ success: true, data } as const)).catch(error => ({ success: false, error }));

        if (!resBody.success) return { ok: true, raw: result.res, error: resBody.error };

        const body = frourioSpec_og4f3x.post.res[200].body.safeParse(resBody.data);

        if (!body.success) return { ok: true, isValid: false, raw: result.res, reason: body.error };

        return {
          ok: true,
          isValid: true,
          data: { status: 200, body: body.data },
          raw: result.res,
        };
      }
      default:
        return { ok: result.res.ok, raw: result.res, error: new Error(`Unknown status: ${result.res.status}`) };
    }
  },
});

const methods_uq501x = (option?: FrourioClientOption) => ({
  async $post(req: { params: z.infer<typeof paramsSchema_uq501x>, body: z.infer<typeof frourioSpec_uq501x.post.body>, init?: RequestInit }): Promise<
    | { ok: true; isValid: true; data: { status: 200; headers?: undefined; body: z.infer<typeof frourioSpec_uq501x.post.res[200]['body']> }; failure?: undefined; raw: Response; reason?: undefined; error?: undefined }
    | { ok: boolean; isValid: false; data?: undefined; failure?: undefined; raw: Response; reason: z.ZodError; error?: undefined }
    | { ok: boolean; isValid?: undefined; data?: undefined; failure?: undefined; raw: Response; reason?: undefined; error: unknown }
    | { ok?: undefined; isValid: false; data?: undefined; failure?: undefined; raw?: undefined; reason: z.ZodError; error?: undefined }
    | { ok?: undefined; isValid?: undefined; data?: undefined; failure?: undefined; raw?: undefined; reason?: undefined; error: unknown }
  > {
    const url = $url_uq501x(option).post(req);

    if (url.reason) return url;

    const parsedBody = frourioSpec_uq501x.post.body.safeParse(req.body);

    if (!parsedBody.success) return { isValid: false, reason: parsedBody.error };

    const fetchFn = option?.fetch ?? fetch;
    const result: { success: true; res: Response } | { success: false; error: unknown } = await fetchFn(
      url.data,
      {
        method: 'POST',
        ...option?.init,
        body: parsedBody.data,
        ...req.init,
        headers: { ...option?.init?.headers, 'content-type': 'application/octet-stream', ...req.init?.headers },
      }
    ).then(res => ({ success: true, res } as const)).catch(error => ({ success: false, error }));

    if (!result.success) return { error: result.error };

    switch (result.res.status) {
      case 200: {
        const resBody: { success: true; data: unknown } | { success: false; error: unknown } = await result.res.blob().then(data => ({ success: true, data } as const)).catch(error => ({ success: false, error }));

        if (!resBody.success) return { ok: true, raw: result.res, error: resBody.error };

        const body = frourioSpec_uq501x.post.res[200].body.safeParse(resBody.data);

        if (!body.success) return { ok: true, isValid: false, raw: result.res, reason: body.error };

        return {
          ok: true,
          isValid: true,
          data: { status: 200, body: body.data },
          raw: result.res,
        };
      }
      default:
        return { ok: result.res.ok, raw: result.res, error: new Error(`Unknown status: ${result.res.status}`) };
    }
  },
});

const methods_bfn325 = (option?: FrourioClientOption) => ({
  async $post(req: { params: z.infer<typeof paramsSchema_bfn325>, body: z.infer<typeof frourioSpec_bfn325.post.body>, init?: RequestInit }): Promise<
    | { ok: true; isValid: true; data: { status: 200; headers?: undefined; body: z.infer<typeof frourioSpec_bfn325.post.res[200]['body']> }; failure?: undefined; raw: Response; reason?: undefined; error?: undefined }
    | { ok: boolean; isValid: false; data?: undefined; failure?: undefined; raw: Response; reason: z.ZodError; error?: undefined }
    | { ok: boolean; isValid?: undefined; data?: undefined; failure?: undefined; raw: Response; reason?: undefined; error: unknown }
    | { ok?: undefined; isValid: false; data?: undefined; failure?: undefined; raw?: undefined; reason: z.ZodError; error?: undefined }
    | { ok?: undefined; isValid?: undefined; data?: undefined; failure?: undefined; raw?: undefined; reason?: undefined; error: unknown }
  > {
    const url = $url_bfn325(option).post(req);

    if (url.reason) return url;

    const parsedBody = frourioSpec_bfn325.post.body.safeParse(req.body);

    if (!parsedBody.success) return { isValid: false, reason: parsedBody.error };

    const fetchFn = option?.fetch ?? fetch;
    const result: { success: true; res: Response } | { success: false; error: unknown } = await fetchFn(
      url.data,
      {
        method: 'POST',
        ...option?.init,
        body: parsedBody.data,
        ...req.init,
        headers: { ...option?.init?.headers, 'content-type': 'text/plain', ...req.init?.headers },
      }
    ).then(res => ({ success: true, res } as const)).catch(error => ({ success: false, error }));

    if (!result.success) return { error: result.error };

    switch (result.res.status) {
      case 200: {
        const resBody: { success: true; data: unknown } | { success: false; error: unknown } = await result.res.text().then(data => ({ success: true, data } as const)).catch(error => ({ success: false, error }));

        if (!resBody.success) return { ok: true, raw: result.res, error: resBody.error };

        const body = frourioSpec_bfn325.post.res[200].body.safeParse(resBody.data);

        if (!body.success) return { ok: true, isValid: false, raw: result.res, reason: body.error };

        return {
          ok: true,
          isValid: true,
          data: { status: 200, body: body.data },
          raw: result.res,
        };
      }
      default:
        return { ok: result.res.ok, raw: result.res, error: new Error(`Unknown status: ${result.res.status}`) };
    }
  },
});

const methods_36xt6y = (option?: FrourioClientOption) => ({
  async $post(req: { body: z.infer<typeof frourioSpec_36xt6y.post.body>, init?: RequestInit }): Promise<
    | { ok: true; isValid: true; data: { status: 200; headers?: undefined; body: z.infer<typeof frourioSpec_36xt6y.post.res[200]['body']> }; failure?: undefined; raw: Response; reason?: undefined; error?: undefined }
    | { ok: boolean; isValid: false; data?: undefined; failure?: undefined; raw: Response; reason: z.ZodError; error?: undefined }
    | { ok: boolean; isValid?: undefined; data?: undefined; failure?: undefined; raw: Response; reason?: undefined; error: unknown }
    | { ok?: undefined; isValid: false; data?: undefined; failure?: undefined; raw?: undefined; reason: z.ZodError; error?: undefined }
    | { ok?: undefined; isValid?: undefined; data?: undefined; failure?: undefined; raw?: undefined; reason?: undefined; error: unknown }
  > {
    const url = $url_36xt6y(option).post();

    if (url.reason) return url;

    const parsedBody = frourioSpec_36xt6y.post.body.safeParse(req.body);

    if (!parsedBody.success) return { isValid: false, reason: parsedBody.error };

    const formData = new FormData();

    Object.entries(parsedBody.data).forEach(([key, value]) => {
      if (value === undefined) return;

      if (Array.isArray(value)) {
        value.forEach((item) =>
          item instanceof File
            ? formData.append(key, item, item.name)
            : formData.append(key, item.toString()),
        );
      } else if (value instanceof File) {
        formData.set(key, value, value.name);
      } else {
        formData.set(key, value.toString());
      }
    });

    const fetchFn = option?.fetch ?? fetch;
    const result: { success: true; res: Response } | { success: false; error: unknown } = await fetchFn(
      url.data,
      {
        method: 'POST',
        ...option?.init,
        body: formData,
        ...req.init,
        headers: { ...option?.init?.headers, ...req.init?.headers },
      }
    ).then(res => ({ success: true, res } as const)).catch(error => ({ success: false, error }));

    if (!result.success) return { error: result.error };

    switch (result.res.status) {
      case 200: {
        const resBody: { success: true; data: unknown } | { success: false; error: unknown } = await result.res.json().then(data => ({ success: true, data } as const)).catch(error => ({ success: false, error }));

        if (!resBody.success) return { ok: true, raw: result.res, error: resBody.error };

        const body = frourioSpec_36xt6y.post.res[200].body.safeParse(resBody.data);

        if (!body.success) return { ok: true, isValid: false, raw: result.res, reason: body.error };

        return {
          ok: true,
          isValid: true,
          data: { status: 200, body: body.data },
          raw: result.res,
        };
      }
      default:
        return { ok: result.res.ok, raw: result.res, error: new Error(`Unknown status: ${result.res.status}`) };
    }
  },
  async $put(req: { body: z.infer<typeof frourioSpec_36xt6y.put.body>, init?: RequestInit }): Promise<
    | { ok: true; isValid: true; data: { status: 200; headers?: undefined; body: z.infer<typeof frourioSpec_36xt6y.put.res[200]['body']> }; failure?: undefined; raw: Response; reason?: undefined; error?: undefined }
    | { ok: boolean; isValid: false; data?: undefined; failure?: undefined; raw: Response; reason: z.ZodError; error?: undefined }
    | { ok: boolean; isValid?: undefined; data?: undefined; failure?: undefined; raw: Response; reason?: undefined; error: unknown }
    | { ok?: undefined; isValid: false; data?: undefined; failure?: undefined; raw?: undefined; reason: z.ZodError; error?: undefined }
    | { ok?: undefined; isValid?: undefined; data?: undefined; failure?: undefined; raw?: undefined; reason?: undefined; error: unknown }
  > {
    const url = $url_36xt6y(option).put();

    if (url.reason) return url;

    const parsedBody = frourioSpec_36xt6y.put.body.safeParse(req.body);

    if (!parsedBody.success) return { isValid: false, reason: parsedBody.error };

    const urlSearchParams = new URLSearchParams();

    Object.entries(parsedBody.data).forEach(([key, value]) => {
      if (value === undefined) return;

      if (Array.isArray(value)) {
        value.forEach((item) => urlSearchParams.append(key, item.toString()));
      } else {
        urlSearchParams.set(key, value.toString());
      }
    });

    const fetchFn = option?.fetch ?? fetch;
    const result: { success: true; res: Response } | { success: false; error: unknown } = await fetchFn(
      url.data,
      {
        method: 'PUT',
        ...option?.init,
        body: urlSearchParams.toString(),
        ...req.init,
        headers: { ...option?.init?.headers, 'content-type': 'application/x-www-form-urlencoded', ...req.init?.headers },
      }
    ).then(res => ({ success: true, res } as const)).catch(error => ({ success: false, error }));

    if (!result.success) return { error: result.error };

    switch (result.res.status) {
      case 200: {
        const resBody: { success: true; data: unknown } | { success: false; error: unknown } = await result.res.json().then(data => ({ success: true, data } as const)).catch(error => ({ success: false, error }));

        if (!resBody.success) return { ok: true, raw: result.res, error: resBody.error };

        const body = frourioSpec_36xt6y.put.res[200].body.safeParse(resBody.data);

        if (!body.success) return { ok: true, isValid: false, raw: result.res, reason: body.error };

        return {
          ok: true,
          isValid: true,
          data: { status: 200, body: body.data },
          raw: result.res,
        };
      }
      default:
        return { ok: result.res.ok, raw: result.res, error: new Error(`Unknown status: ${result.res.status}`) };
    }
  },
});

const methods_15e5upz = (option?: FrourioClientOption) => ({
  async $post(req: { body: z.infer<typeof frourioSpec_15e5upz.post.body>, init?: RequestInit }): Promise<
    | { ok: true; isValid: true; data: { status: 200; headers?: undefined; body: z.infer<typeof frourioSpec_15e5upz.post.res[200]['body']> }; failure?: undefined; raw: Response; reason?: undefined; error?: undefined }
    | { ok: boolean; isValid: false; data?: undefined; failure?: undefined; raw: Response; reason: z.ZodError; error?: undefined }
    | { ok: boolean; isValid?: undefined; data?: undefined; failure?: undefined; raw: Response; reason?: undefined; error: unknown }
    | { ok?: undefined; isValid: false; data?: undefined; failure?: undefined; raw?: undefined; reason: z.ZodError; error?: undefined }
    | { ok?: undefined; isValid?: undefined; data?: undefined; failure?: undefined; raw?: undefined; reason?: undefined; error: unknown }
  > {
    const url = $url_15e5upz(option).post();

    if (url.reason) return url;

    const parsedBody = frourioSpec_15e5upz.post.body.safeParse(req.body);

    if (!parsedBody.success) return { isValid: false, reason: parsedBody.error };

    const formData = new FormData();

    Object.entries(parsedBody.data).forEach(([key, value]) => {
      if (value === undefined) return;

      if (Array.isArray(value)) {
        value.forEach((item) =>
          item instanceof File
            ? formData.append(key, item, item.name)
            : formData.append(key, item.toString()),
        );
      } else if (value instanceof File) {
        formData.set(key, value, value.name);
      } else {
        formData.set(key, value.toString());
      }
    });

    const fetchFn = option?.fetch ?? fetch;
    const result: { success: true; res: Response } | { success: false; error: unknown } = await fetchFn(
      url.data,
      {
        method: 'POST',
        ...option?.init,
        body: formData,
        ...req.init,
        headers: { ...option?.init?.headers, ...req.init?.headers },
      }
    ).then(res => ({ success: true, res } as const)).catch(error => ({ success: false, error }));

    if (!result.success) return { error: result.error };

    switch (result.res.status) {
      case 200: {
        const resBody: { success: true; data: unknown } | { success: false; error: unknown } = await result.res.json().then(data => ({ success: true, data } as const)).catch(error => ({ success: false, error }));

        if (!resBody.success) return { ok: true, raw: result.res, error: resBody.error };

        const body = frourioSpec_15e5upz.post.res[200].body.safeParse(resBody.data);

        if (!body.success) return { ok: true, isValid: false, raw: result.res, reason: body.error };

        return {
          ok: true,
          isValid: true,
          data: { status: 200, body: body.data },
          raw: result.res,
        };
      }
      default:
        return { ok: result.res.ok, raw: result.res, error: new Error(`Unknown status: ${result.res.status}`) };
    }
  },
});

