/* This is code generated by @frourio/vinext. Do not edit directly. */
import { z } from 'zod';
import { frourioSpec } from './frourio';

export const paramsSchema = z.object({ 'fuga': frourioSpec.param });

export type ParamsType = z.infer<typeof paramsSchema>;

export type NextParams<T extends Record<string, unknown>> = {
  [Key in keyof T]: (NonNullable<T[Key]> extends unknown[] ? string[] : string) | T[Key];
};
