/* This is code generated by @frourio/vinext. Do not edit directly. */
import { type NextRequest, NextResponse } from 'vinext/shims/server';
import type { z } from 'zod';
import { frourioSpec } from './frourio';
import type { GET, POST, DELETE } from './route';

type RouteChecker = [typeof GET, typeof POST, typeof DELETE];

type SpecType = typeof frourioSpec;

type Controller = {
  get: (
    req: {
      headers: z.infer<SpecType['get']['headers']>;
    },
  ) => Promise<NextResponse | Response>;
  post: (
    req: {
      headers: z.infer<SpecType['post']['headers']>;
    },
  ) => Promise<NextResponse | Response>;
  delete: (
    req: {
    },
  ) => Promise<
    | {
        status: 400;
        headers: z.infer<SpecType['delete']['res'][400]['headers']>;
        body: z.infer<SpecType['delete']['res'][400]['body']>;
      }
  >;
};

type MethodHandler = (req: NextRequest | Request) => Promise<NextResponse>;

type ResHandler = {
  GET: MethodHandler
  POST: MethodHandler
  DELETE: MethodHandler
};

export const createRoute = (controller: Controller): ResHandler => {
  return {
    GET: async (req) => {
      const headers = frourioSpec.get.headers.safeParse(Object.fromEntries(req.headers));

      if (headers.error) return createReqErr(headers.error);

      const res = await controller.get({ headers: headers.data });

      return res instanceof NextResponse ? res : new NextResponse(res.body, res);
    },
    POST: async (req) => {
      const headers = frourioSpec.post.headers.safeParse(Object.fromEntries(req.headers));

      if (headers.error) return createReqErr(headers.error);

      const res = await controller.post({ headers: headers.data });

      return res instanceof NextResponse ? res : new NextResponse(res.body, res);
    },
    DELETE: async (req) => {
      const res = await controller.delete({  });

      switch (res.status) {
        case 400: {
          const headers = frourioSpec.delete.res[400].headers.safeParse(res.headers);

          if (headers.error) return createResErr();

          const body = frourioSpec.delete.res[400].body.safeParse(res.body);

          if (body.error) return createResErr();

          return createResponse(body.data, { status: 400, headers: headers.data });
        }
        default:
          throw new Error(res.status satisfies never);
      }
    },
  };
};

const createResponse = (body: unknown, init: ResponseInit): NextResponse => {
  if (
    ArrayBuffer.isView(body) ||
    body === undefined ||
    body === null ||
    body instanceof Blob ||
    body instanceof ArrayBuffer ||
    body instanceof FormData ||
    body instanceof ReadableStream ||
    body instanceof URLSearchParams ||
    typeof body === 'string'
  ) {
    return new NextResponse(body as string, init);
  }

  return NextResponse.json(body, init);
};

type FrourioError =
  | { status: 422; error: string; issues: { path: (string | number)[]; message: string }[] }
  | { status: 500; error: string; issues?: undefined };

const createReqErr = (err: z.ZodError) =>
  NextResponse.json<FrourioError>(
    {
      status: 422,
      error: 'Unprocessable Entity',
      issues: err.issues.map((issue) => ({ path: issue.path.filter(p => typeof p !== 'symbol'), message: issue.message })),
    },
    { status: 422 },
  );

const createResErr = () =>
  NextResponse.json<FrourioError>(
    { status: 500, error: 'Internal Server Error' },
    { status: 500 },
  );
