/* This is code generated by @frourio/vinext. Do not edit directly. */
import { type NextRequest, NextResponse } from 'vinext/shims/server';
import type { z } from 'zod';
import { middleware as ancestorMiddleware } from '../route.middleware';
import { frourioSpec } from './frourio';

export const contextSchema = frourioSpec.middleware.context;

export type ContextType = z.infer<typeof contextSchema>;

type MiddlewareFn = (
  args: {
    req: NextRequest | Request,
    cookies: z.infer<typeof frourioSpec.middleware.cookies>,
    next: (ctx: z.infer<typeof frourioSpec.middleware.context>) => Promise<NextResponse>,
  },
) => Promise<NextResponse>;

type MiddlewareHandler = (
  next: (args: { req: NextRequest | Request }, ctx: ContextType) => Promise<NextResponse>,
) => (req: NextRequest | Request, option?: Record<string, unknown>) => Promise<NextResponse>;

export const createMiddleware = (middlewareFn: MiddlewareFn): MiddlewareHandler => {
  return (
    next: (args: { req: NextRequest | Request }, ctx: ContextType) => Promise<NextResponse>,
  ) => async (req: NextRequest | Request, _option?: Record<string, unknown>) => {
    return ancestorMiddleware(async () => {

    const cookies = frourioSpec.middleware.cookies.safeParse(parseCookieHeader(req.headers.get('cookie')));
    if (cookies.error) return createReqErr(cookies.error);
    return await middlewareFn(
      {
        req,
        cookies: cookies.data,
        next: async ( context) => {
          const ctx = frourioSpec.middleware.context.safeParse(context);

          if (ctx.error) return createReqErr(ctx.error);

          return await next({ req }, ctx.data);
        },
      },
    );
    })(req);
  };
};
const parseCookieHeader = (header: string | null): Record<string, string> => {
  const cookies: Record<string, string> = Object.create(null);

  for (const segment of (header ?? '').split(';')) {
    const separator = segment.indexOf('=');
    if (separator < 0) continue;

    const name = segment.slice(0, separator).trim();
    if (!name || name in cookies) continue;

    let value = segment.slice(separator + 1).trim();
    if (value.startsWith('"') && value.endsWith('"')) value = value.slice(1, -1);

    try {
      cookies[name] = decodeURIComponent(value);
    } catch {
      cookies[name] = value;
    }
  }

  return cookies;
};

type FrourioError =
  | { status: 422; error: string; issues: { path: (string | number)[]; message: string }[] }
  | { status: 500; error: string; issues?: undefined };

const createReqErr = (err: z.ZodError) =>
  NextResponse.json<FrourioError>(
    {
      status: 422,
      error: 'Unprocessable Entity',
      issues: err.issues.map((issue) => ({ path: issue.path.filter(p => typeof p !== 'symbol'), message: issue.message })),
    },
    { status: 422 },
  );
